# YAML file location : config/

application:
  name: OrderSync
  version: 1.0.0
  log_directory: c:\winparf\logs
  log_level: INFO
# int en numéro de semaines. Fenêtre arrière pour mettre à jour les commandes dans COMMANDE et LGCDE. Absence, "0" ou negatif => fenêtre de filtrage désactivée.
  maj_periode: 56

hyperfile:
  provider: PCSOFT.HFSQL
  repository: C:\winparf\data
  password: WP2017NF525

sqlserver:
  driver: "ODBC Driver 18 for SQL Server"
  server: W10\SQLEXPRESS
  database: WINPARF
  trusted_connection: true
  username: ""
  password: ""
  timeout: 30