-- SQL script location : sql/
USE [{DB_NAME}];

-- COMMANDE table creation
CREATE TABLE COMMANDE (
    TYPCDE VARCHAR(1) NOT NULL,
    NOCDE VARCHAR(7) NOT NULL,
    CFOUR VARCHAR(4) NOT NULL,
    CCOMPTE VARCHAR(2) NULL,
    LIBCDE VARCHAR(25) NULL,
    DTCDE DATE NOT NULL,
    HEURECDE VARCHAR(4) NULL,
    NOCHRONO VARCHAR(6) NULL,
    OBSER VARCHAR(100) NULL,
    MODECDE VARCHAR(1) NULL,
    DTLIVPREVU DATE NULL,
    DTREGLEMN DATE NULL,
    NBJOURS VARCHAR(3) NULL,
    CDECENTRAL TINYINT NULL,
    TXREM VARCHAR(15) NULL,
    MTCDE FLOAT NULL,
    MTRECU FLOAT NULL,
    ARTSUPP VARCHAR(1) NULL,
    CETIQ VARCHAR(1) NULL,
    TYPRECEP VARCHAR(1) NULL,
    MAGCDE VARCHAR(300) NULL,
    MAGLIVR VARCHAR(4) NULL,
    MAGFACTURE VARCHAR(4) NULL,
    MAGLIVRADR VARCHAR(4) NULL,
    DEVISE VARCHAR(3) NULL,
    TXCHGLOCAL REAL NULL,
    TXREMPIED VARCHAR(15) NULL,
    ESCOMPTE REAL NULL,
    FACTHT VARCHAR(1) NULL,
    MTDEVISE FLOAT NULL,
    UNICDE_O_N VARCHAR(1) NULL,
    RETOUR_CDE VARCHAR(1) NULL,
    CDEFPERM VARCHAR(1) NULL,
    MTCDETTC FLOAT NULL,
    MTRECUTTC FLOAT NULL,
    COEF REAL NULL,
    BMEMOFACT INT NULL,
    DTREC DATE NULL,
    DTFACT DATE NULL,
    DESTINCDE VARCHAR(1) NULL,
    FORMAT_EDI TINYINT NULL,
    TYPEPERM TINYINT NULL,
    AFFSTKMG TINYINT NULL,
    PERMTOTAL TINYINT NULL,
    CHCATSEL VARCHAR(100) NULL,
    CHLIGSEL VARCHAR(100) NULL,
    NOFACTFOUR VARCHAR(10) NULL,
    CMODREGL VARCHAR(3) NULL,
    DTENLEVMARCH DATE NULL,
    HRENLEVMARCH VARCHAR(4) NULL,
    MAGFACTADR VARCHAR(4) NULL,
    ADRDESTLIVR VARCHAR(1) NULL,
    ADRDESTFACT VARCHAR(1) NULL,
    QTEACH INT NULL,
    STKARTRPL TINYINT NULL,
    IGNOREMINICDE TINYINT NULL,
    STATUTEDI VARCHAR(1) NULL,
    CDENUMPLF VARCHAR(100) NULL,
    DTLIVREDI DATE NULL,
    DTLIVRPROD DATE NULL,
    MINILGCDE DECIMAL(18,4) NULL,
    TYPE_ORDER VARCHAR(1) NULL,
    REFNUMEXT VARCHAR(30) NULL,
    NOLOT VARCHAR(13) NULL,
    CHTYPINVEND VARCHAR(100) NULL,

    CONSTRAINT PK_COMMANDE PRIMARY KEY (NOCDE)
);

-- LGCDE Table creation
CREATE TABLE LGCDE (
    TYPCDE VARCHAR(1) NOT NULL,
    NOCDE VARCHAR(7) NOT NULL,
    CMARQ VARCHAR(3) NOT NULL,
    CLIGNE VARCHAR(2) NULL,
    CCATEG VARCHAR(2) NOT NULL,
    CPROD VARCHAR(3) NOT NULL,
    PADEVISE FLOAT NULL,
    PAAR FLOAT NULL,
    PAMP FLOAT NULL,
    QTESTK INT NULL,
    QTECDE INT NULL,
    QTEGRT SMALLINT NULL,
    TXREM VARCHAR(15) NULL,
    CDEMANUEL INT NULL,
    CTVA VARCHAR(2) NULL,
    TVA REAL NULL,
    STATUS_LCDE INT NULL,
    STATUS_RCDE INT NULL,
    RAZMINI VARCHAR(1) NULL,
    QTERECU INT NULL,
    QTEGRTRECU SMALLINT NULL,
    TYPRECEP VARCHAR(1) NULL,
    QTEREFUS INT NULL,
    MTLIGDEV FLOAT NULL,
    MTLIG FLOAT NULL,
    CRCLGCDE INT NULL,
    QTEFAC INT NULL,
    QTEGRTFAC SMALLINT NULL,
    QTEBL INT NULL,
    CONDACH REAL NULL,
    QTEABIME INT NULL,
    SCONDSPEC INT NULL,
    COEF REAL NULL,
    QTEFACEDI INT NULL,
    PAEDI REAL NULL,
    TXREMEDI REAL NULL,
    TXREMFAC REAL NULL,
    PAFAC REAL NULL,
    MTLIGFAC DECIMAL(18,4) NULL,
    TYPINVEND VARCHAR(2) NULL,

    CONSTRAINT FK_LGCDE_COMMANDE
        FOREIGN KEY (NOCDE)
        REFERENCES COMMANDE(NOCDE)
);

CREATE UNIQUE INDEX UX_LGCDE_ORDER_PRODUCT
ON LGCDE (
    NOCDE,
    CMARQ,
    CCATEG,
    CPROD
);

-- Performance index creation
CREATE INDEX IX_COMMANDE_DTCDE_TYPCDE
ON COMMANDE (DTCDE, TYPCDE);

CREATE INDEX IX_LGCDE_NOCDE
ON LGCDE (NOCDE);

